# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticounterfeit', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=b'/home/akelsaman/git/hikma/hikma/html/images/product-original.jpg', upload_to=b'images'),
        ),
    ]
