# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anticounterfeit', '0004_auto_20151207_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='cityFK',
            new_name='City',
        ),
        migrations.AlterUniqueTogether(
            name='pharmacy',
            unique_together=set([('pharmacy', 'City')]),
        ),
    ]
