# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anticounterfeit', '0006_auto_20151207_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='State',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='anticounterfeit.State'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='City',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='anticounterfeit.City'),
        ),
        migrations.AlterField(
            model_name='publiccode',
            name='Product',
            field=models.ForeignKey(default=b'1', on_delete=django.db.models.deletion.PROTECT, to='anticounterfeit.Product'),
        ),
        migrations.AlterField(
            model_name='usercode',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anticounterfeit.Product'),
        ),
    ]
