# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anticounterfeit', '0007_auto_20151207_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiccode',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='anticounterfeit.Product'),
        ),
    ]
