# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anticounterfeit', '0009_auto_20151207_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='State',
            new_name='RState',
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set([('city', 'RState')]),
        ),
    ]
