# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anticounterfeit', '0010_auto_20151207_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='RState',
            new_name='State',
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set([('city', 'State')]),
        ),
    ]
