# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticounterfeit', '0012_auto_20151207_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=30, unique=True, verbose_name=b'City'),
        ),
    ]
