# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticounterfeit', '0013_auto_20151207_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='pharmacy',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='publiccode',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='usercode',
            old_name='Product',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set([('city', 'state')]),
        ),
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together=set([('doctor', 'city')]),
        ),
        migrations.AlterUniqueTogether(
            name='pharmacy',
            unique_together=set([('pharmacy', 'city')]),
        ),
    ]
