# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anticounterfeit', '0015_auto_20151207_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='productImage',
        ),
    ]
