# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anticounterfeit', '0017_auto_20151207_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checker', models.CharField(max_length=20, unique=True, verbose_name=b'State')),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='cityPK',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='doctorPK',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='pharmacyPK',
        ),
        migrations.RemoveField(
            model_name='publiccode',
            name='publicCodePK',
        ),
        migrations.RemoveField(
            model_name='state',
            name='statePK',
        ),
        migrations.RemoveField(
            model_name='usercode',
            name='userCodePK',
        ),
        migrations.AddField(
            model_name='city',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publiccode',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercode',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='check',
            name='doctorFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anticounterfeit.Doctor'),
        ),
        migrations.AddField(
            model_name='check',
            name='pharmacyFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anticounterfeit.Pharmacy'),
        ),
        migrations.AddField(
            model_name='check',
            name='productFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anticounterfeit.Product'),
        ),
    ]
