# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticounterfeit', '0018_auto_20151210_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productPK',
            new_name='id',
        ),
        migrations.AddField(
            model_name='check',
            name='checkerEmail',
            field=models.CharField(default=1, max_length=50, verbose_name=b'Cheaker Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='check',
            name='checkerMobile',
            field=models.CharField(default=8, max_length=50, verbose_name=b'Cheaker Mobile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='check',
            name='checker',
            field=models.CharField(max_length=50, verbose_name=b'Checker'),
        ),
    ]
